name: Python tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install system dependencies
      run: |
         sudo apt install -y build-essential libpoppler-cpp-dev pkg-config python3-dev
                
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test building documentation
      run: |
        cd docs
        make html
    - name: Check code style
      run: |
        flake8 yaramail
    - name: Test building packages
      run: hatch build
    - name: Test rules
      run: python3 -m yaramail._cli -t --rules test test\samples